# Generated by Django 4.1.7 on 2023-03-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Home_logo',
            new_name='home_logo',
        ),
    ]
