# Generated by Django 4.1.7 on 2023-03-28 05:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_card_title', models.CharField(max_length=20)),
                ('service_card_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
