# Generated by Django 4.1.7 on 2023-03-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicecards_alter_service_service_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecards',
            old_name='service_card_desc',
            new_name='service_card_intro',
        ),
    ]
