# Generated by Django 4.1.7 on 2023-03-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_service_card_desc_servicecards_service_card_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_des',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_title',
        ),
    ]
