# Generated by Django 4.1.7 on 2023-03-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_service_service_des_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
