# Generated by Django 4.1.7 on 2023-03-28 09:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=20)),
                ('service_title', models.CharField(max_length=50)),
                ('service_des', tinymce.models.HTMLField()),
            ],
        ),
    ]
