# Generated by Django 4.1.7 on 2023-03-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCards',
        ),
    ]
