# Generated by Django 4.1.7 on 2023-03-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicecard_alter_service_service_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='service_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='service/'),
        ),
    ]
