# Generated by Django 4.1.7 on 2023-03-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(max_length=10)),
            ],
        ),
    ]
